# .github/workflows/chromatic.yml

# Workflow name
name: "Chromatic Publish"

# Event for the workflow
on: push

# List of jobs
jobs:
  build-storybook:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.x
      - name: Checkout
        uses: actions/checkout@v3
      - name: install dependencies
        run: pnpm install
      #👇 Adds Chromatic as a step in the workflow
      - uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken,
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
